# Generated by Django 6.0.3 on 2026-03-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparringrequest',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='sparringrequest',
            name='equipment_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sparringrequest',
            name='martial_art',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
