# Generated by Django 6.0.3 on 2026-03-28 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('weight_class', models.CharField(blank=True, choices=[('flyweight', 'Flyweight (-57kg)'), ('bantamweight', 'Bantamweight (-61kg)'), ('featherweight', 'Featherweight (-66kg)'), ('lightweight', 'Lightweight (-70kg)'), ('welterweight', 'Welterweight (-77kg)'), ('middleweight', 'Middleweight (-84kg)'), ('light_heavyweight', 'Light Heavyweight (-93kg)'), ('heavyweight', 'Heavyweight (+93kg)')], max_length=20)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
