# Generated by Django 6.0.3 on 2026-03-28 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('focus', models.CharField(choices=[('striking', 'Striking'), ('grappling', 'Grappling'), ('conditioning', 'Physical Conditioning'), ('sparring', 'Sparring'), ('technique', 'Technique Drills')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('intensity', models.PositiveSmallIntegerField(choices=[(1, 'Very Light'), (2, 'Light'), (3, 'Moderate'), (4, 'Hard'), (5, 'Max Effort')], default=3)),
                ('notes', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
